# The recommended basic settings for GNN
dataset:
  format: PyG
  name: Cora
  task: node
  task_type: classification
  transductive: True
  split: [0.7, 0.1, 0.2]
  augment_feature: []
  augment_feature_dims: [0]
  augment_feature_repr: position
  augment_label: ''
  augment_label_dims: 0
  transform: none
train:
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_mp: 2
  layers_post_mp: 1
  dim_inner: 64
  layer_type: generalconv 
  # layer_type: splineconv 
  # conv_kwargs: ['chebconv':{'K':2}, 'splineconv':{'dim':1, 'kernel_size':2}]
  stage_type: stack
  batchnorm: True
  act: elu
  dropout: 0.5
  agg: add
  normalize_adj: False
optim:
  optimizer: adam
  base_lr: 0.001
  max_epoch: 200