dataset:
  format: OGB
  name: ogbn-proteins
  task: node
  task_type:  multi-tasks-classification
  node_encoder: False
  node_encoder_name: Atom
  edge_encoder: False
  edge_encoder_name: Bond
  edge_dim : 8
share:
  dim_out: 112
train:
  batch_size: 32
  eval_period: 10
  ckpt_period: 100
  sampler: full_batch
model:
  type: gnn
  loss_fun: bce
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_mp: 4
  layers_post_mp: 1
  dim_inner: 64
  layer_type: generalconv
  stage_type: skipsum
  batchnorm: True
  act: prelu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 1000