out_dir: run/results/molhiv/
dataset:
  format: OGB
  name: ogbg-molhiv
  task: graph
  task_type: classification
  node_encoder: True
  node_encoder_name: Atom
  edge_encoder: True
  edge_encoder_name: Bond
train:
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
  sampler: full_batch
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 2
  layers_mp: 6
  layers_post_mp: 3
  dim_inner: 128
  layer_type: generalconv
  stage_type: skipconcat
  batchnorm: True
  act: prelu
  dropout: 0.0
  agg: add
  normalize_adj: False
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 100