dataset:
  format: PyG
  task: graph
  task_type: classification
  node_encoder: False
  edge_encoder: False
train:
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
  sampler: full_batch
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_mp: 2
  layers_post_mp: 1
  dim_inner: 128
  layer_type: generaledgeconv
  stage_type: stack
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
  pool_type: topk
  pool_loop: 3
  pool_ratio: 0.5
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 150