"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SEND_TRIAL_JOB_PARAMETER = exports.TRIAL_COMMANDS = exports.ASSESSOR_COMMANDS = exports.TUNER_COMMANDS = exports.KILL_TRIAL_JOB = exports.NO_MORE_TRIAL_JOBS = exports.NEW_TRIAL_JOB = exports.INITIALIZED = exports.VERSION_CHECK = exports.STDOUT = exports.GPU_INFO = exports.PING = exports.TERMINATE = exports.TRIAL_END = exports.ADD_CUSTOMIZED_TRIAL_JOB = exports.IMPORT_DATA = exports.UPDATE_SEARCH_SPACE = exports.REPORT_METRIC_DATA = exports.REQUEST_TRIAL_JOBS = exports.INITIALIZE = void 0;
const INITIALIZE = 'IN';
exports.INITIALIZE = INITIALIZE;
const REQUEST_TRIAL_JOBS = 'GE';
exports.REQUEST_TRIAL_JOBS = REQUEST_TRIAL_JOBS;
const REPORT_METRIC_DATA = 'ME';
exports.REPORT_METRIC_DATA = REPORT_METRIC_DATA;
const UPDATE_SEARCH_SPACE = 'SS';
exports.UPDATE_SEARCH_SPACE = UPDATE_SEARCH_SPACE;
const IMPORT_DATA = 'FD';
exports.IMPORT_DATA = IMPORT_DATA;
const ADD_CUSTOMIZED_TRIAL_JOB = 'AD';
exports.ADD_CUSTOMIZED_TRIAL_JOB = ADD_CUSTOMIZED_TRIAL_JOB;
const TRIAL_END = 'EN';
exports.TRIAL_END = TRIAL_END;
const TERMINATE = 'TE';
exports.TERMINATE = TERMINATE;
const PING = 'PI';
exports.PING = PING;
const GPU_INFO = 'GI';
exports.GPU_INFO = GPU_INFO;
const STDOUT = 'SO';
exports.STDOUT = STDOUT;
const VERSION_CHECK = 'VC';
exports.VERSION_CHECK = VERSION_CHECK;
const INITIALIZED = 'ID';
exports.INITIALIZED = INITIALIZED;
const NEW_TRIAL_JOB = 'TR';
exports.NEW_TRIAL_JOB = NEW_TRIAL_JOB;
const SEND_TRIAL_JOB_PARAMETER = 'SP';
exports.SEND_TRIAL_JOB_PARAMETER = SEND_TRIAL_JOB_PARAMETER;
const NO_MORE_TRIAL_JOBS = 'NO';
exports.NO_MORE_TRIAL_JOBS = NO_MORE_TRIAL_JOBS;
const KILL_TRIAL_JOB = 'KI';
exports.KILL_TRIAL_JOB = KILL_TRIAL_JOB;
const TRIAL_COMMANDS = new Set([
    NEW_TRIAL_JOB,
    SEND_TRIAL_JOB_PARAMETER,
    KILL_TRIAL_JOB,
    INITIALIZED,
    TRIAL_END,
    GPU_INFO,
    STDOUT,
    VERSION_CHECK,
]);
exports.TRIAL_COMMANDS = TRIAL_COMMANDS;
const TUNER_COMMANDS = new Set([
    INITIALIZE,
    REQUEST_TRIAL_JOBS,
    REPORT_METRIC_DATA,
    UPDATE_SEARCH_SPACE,
    IMPORT_DATA,
    ADD_CUSTOMIZED_TRIAL_JOB,
    TERMINATE,
    PING,
    INITIALIZED,
    NEW_TRIAL_JOB,
    SEND_TRIAL_JOB_PARAMETER,
    NO_MORE_TRIAL_JOBS
]);
exports.TUNER_COMMANDS = TUNER_COMMANDS;
const ASSESSOR_COMMANDS = new Set([
    INITIALIZE,
    REPORT_METRIC_DATA,
    TRIAL_END,
    TERMINATE,
    KILL_TRIAL_JOB
]);
exports.ASSESSOR_COMMANDS = ASSESSOR_COMMANDS;
